# numpy

In [4]:
import numpy as np

In [5]:
li = [2,4,3, 1, 0]
print(li, type(li))

arr = np.array(li)
print(arr, type(arr))
print(f'arr.ndim    =>  {arr.ndim}')
print(f'arr.shape   =>  {arr.shape}')
print(f'arr.dtype   =>  {arr.dtype}')
print(f'arr.size    =>  {arr.size}')
print(f'len(arr)    =>  {len(arr)}')

# arr = np.array(4,3,1,4)  # ValueError: only 2 non-keyword arguments accepted

[2, 4, 3, 1, 0] <class 'list'>
[2 4 3 1 0] <class 'numpy.ndarray'>
arr.ndim    =>  1
arr.shape   =>  (5,)
arr.dtype   =>  int32
arr.size    =>  5
len(arr)    =>  5


In [6]:
arr = np.array([[9.0, 3.4, 5],[4.5, 6.0]])
print(arr, type(arr))
print(f'arr.ndim    =>  {arr.ndim}')
print(f'arr.shape   =>  {arr.shape}')
print(f'arr.dtype   =>  {arr.dtype}') # object
print("--------------------------------------------------")

arr = np.array([[9.0, 3.4, 5],[4.5, 6.0, 8]])
print(arr, type(arr))
print(f'arr.ndim    =>  {arr.ndim}')
print(f'arr.shape   =>  {arr.shape}')
print(f'arr.dtype   =>  {arr.dtype}') # float64
print(f'arr.size    =>  {arr.size}')
print(f'len(arr)    =>  {len(arr)}')

[list([9.0, 3.4, 5]) list([4.5, 6.0])] <class 'numpy.ndarray'>
arr.ndim    =>  1
arr.shape   =>  (2,)
arr.dtype   =>  object
--------------------------------------------------
[[9.  3.4 5. ]
 [4.5 6.  8. ]] <class 'numpy.ndarray'>
arr.ndim    =>  2
arr.shape   =>  (2, 3)
arr.dtype   =>  float64
arr.size    =>  6
len(arr)    =>  2


In [7]:
arr = np.array([3, 4, 2], dtype='int16')
print(f'arr             =>  {arr}')
print(f'arr.dtype       =>  {arr.dtype}')
print(f'arr.itemsize    =>  {arr.itemsize}')
print(f'arr.size        =>  {arr.size}')
print(f'len(arr)        =>  {len(arr)}')
print(f'arr.nbytes      =>  {arr.nbytes}')
# arr.dtype = 'int32' # ValueError: When changing to a larger dtype, its size must be a divisor of the total size in bytes of the last axis of the array.

arr             =>  [3 4 2]
arr.dtype       =>  int16
arr.itemsize    =>  2
arr.size        =>  3
len(arr)        =>  3
arr.nbytes      =>  6


In [8]:
arr = np.array([3, 4, 2, 8], dtype='int16')
print(f'arr             =>  {arr}')
print(f'arr.dtype       =>  {arr.dtype}')
print(f'arr.itemsize    =>  {arr.itemsize}')
print(f'arr.size        =>  {arr.size}')
print(f'len(arr)        =>  {len(arr)}')
print(f'arr.nbytes      =>  {arr.nbytes}')
print("--------------------------------------------------")

arr.dtype = 'int32'
print(f'arr             =>  {arr}') #  # garbage values
print(f'arr.dtype       =>  {arr.dtype}')
print(f'arr.itemsize    =>  {arr.itemsize}')
print(f'arr.size        =>  {arr.size}')
print(f'len(arr)        =>  {len(arr)}')
print(f'arr.nbytes      =>  {arr.nbytes}')

arr             =>  [3 4 2 8]
arr.dtype       =>  int16
arr.itemsize    =>  2
arr.size        =>  4
len(arr)        =>  4
arr.nbytes      =>  8
--------------------------------------------------
arr             =>  [262147 524290]
arr.dtype       =>  int32
arr.itemsize    =>  4
arr.size        =>  2
len(arr)        =>  2
arr.nbytes      =>  8


## numpy array shape, reshape()

In [9]:
arr = np.array([2,5,3,4,4,7])
print(arr.shape)

arr.shape = (2,3)
print(f'arr         =>  {arr}')
print(f'arr.shape   =>  {arr.shape}')
print(f'arr.size    =>  {arr.size}')
print(f'len(arr)    =>  {len(arr)}')
print("------------------------------------------------------------------------")

arr = np.array([2,5,3,4,4,7])
print(arr.shape)

arr2 = arr.reshape(2,3)
print(f'arr         =>  {arr}')
print(f'arr.shape   =>  {arr.shape}')
print(f'arr.size    =>  {arr.size}')
print(f'len(arr)    =>  {len(arr)}')
print(f'arr2        =>  {arr2}')
print(f'arr2.shape  =>  {arr2.shape}')
print(f'arr2.size   =>  {arr2.size}')
print(f'len(arr2)   =>  {len(arr2)}')

(6,)
arr         =>  [[2 5 3]
 [4 4 7]]
arr.shape   =>  (2, 3)
arr.size    =>  6
len(arr)    =>  2
------------------------------------------------------------------------
(6,)
arr         =>  [2 5 3 4 4 7]
arr.shape   =>  (6,)
arr.size    =>  6
len(arr)    =>  6
arr2        =>  [[2 5 3]
 [4 4 7]]
arr2.shape  =>  (2, 3)
arr2.size   =>  6
len(arr2)   =>  2


## Converting numpy arrays to list, set etc.

In [10]:
li = [1, 2, 3, 2]
print(li, type(li))

arr = np.array(li)
print(arr, type(arr))

li = list(arr)
print(li, type(li))

s = set(arr)
print(s, type(s))

tu = tuple(arr)
print(tu, type(tu))


[1, 2, 3, 2] <class 'list'>
[1 2 3 2] <class 'numpy.ndarray'>
[1, 2, 3, 2] <class 'list'>
{1, 2, 3} <class 'set'>
(1, 2, 3, 2) <class 'tuple'>


## numpy array iterating

In [11]:
arr = np.array([[1,2,3], [4,5,6]])

for a in arr:
    for b in a:
        print(b, end=' ')
print()
print("------------------------------------------------------------------------")

# # Iterating on each scalar element #

for element in np.nditer(arr):
    print(element, end=' ')
print()

for posn, element in np.ndenumerate(arr):
    print(posn, element, end=' | ')
print()

for (i, j), element in np.ndenumerate(arr):
    print(f'{i},{j} - {element}', end=' | ')
print()
print("------------------------------------------------------------------------")

mat = [[1,2,3], [4,5,6]]
for posn, element in np.ndenumerate(mat):
    print(posn, element, end=' | ')
print()

for (i, j), element in np.ndenumerate(mat):
    print(f'{i},{j} - {element}', end=' | ')
print()


1 2 3 4 5 6 
------------------------------------------------------------------------
1 2 3 4 5 6 
(0, 0) 1 | (0, 1) 2 | (0, 2) 3 | (1, 0) 4 | (1, 1) 5 | (1, 2) 6 | 
0,0 - 1 | 0,1 - 2 | 0,2 - 3 | 1,0 - 4 | 1,1 - 5 | 1,2 - 6 | 
------------------------------------------------------------------------
(0, 0) 1 | (0, 1) 2 | (0, 2) 3 | (1, 0) 4 | (1, 1) 5 | (1, 2) 6 | 
0,0 - 1 | 0,1 - 2 | 0,2 - 3 | 1,0 - 4 | 1,1 - 5 | 1,2 - 6 | 


## numpy array slice

In [12]:
arr = np.array([[1, 2, 3, 4, 5], [10, 20, 30, 40, 50], [100, 200, 300, 400, 500]])
print(arr)
arr[1:, 1:4] += 5
print(arr)
print("------------------------------------------------------------------------")

arr_slice = arr[1:, 1:4]
arr_slice += 5
print(arr)

[[  1   2   3   4   5]
 [ 10  20  30  40  50]
 [100 200 300 400 500]]
[[  1   2   3   4   5]
 [ 10  25  35  45  50]
 [100 205 305 405 500]]
------------------------------------------------------------------------
[[  1   2   3   4   5]
 [ 10  30  40  50  50]
 [100 210 310 410 500]]


## numpy array slice, copy()

In [13]:
arr = np.arange(5)
print(arr)
arr_slice = arr[1:4]
arr_slice1 = arr[1:4]
arr_slice2 = arr[1:4].copy()

# arr_slice[1] = [9, 4] # ValueError: setting an array element with a sequence.
# arr_slice[10] = 9 # IndexError: index 10 is out of bounds for axis 0 with size 3
arr_slice[0] = 8
print(arr, arr_slice, arr_slice1, arr_slice2)

arr_slice2[1] = 9
print(arr, arr_slice, arr_slice1, arr_slice2)

arr2 = arr
arr3 = arr.copy()
arr[0] = 999
print(arr, arr2, arr3)

[0 1 2 3 4]
[0 8 2 3 4] [8 2 3] [8 2 3] [1 2 3]
[0 8 2 3 4] [8 2 3] [8 2 3] [1 9 3]
[999   8   2   3   4] [999   8   2   3   4] [0 8 2 3 4]


## np.zeros(), np.ones()

In [14]:
z = np.zeros(10)
o = np.ones(10)
print(z, o)
print(z.dtype, o.dtype)
print("------------------------------------------------------------------------")

z = np.zeros(10, dtype=np.int32)
o = np.ones(10, dtype='i4')
print(z)
print(o)
print("------------------------------------------------------------------------")

z = np.zeros(shape=(3, 4), dtype='i2')
o = np.ones((2, 3))
print(z)
print(o)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
float64 float64
------------------------------------------------------------------------
[0 0 0 0 0 0 0 0 0 0]
[1 1 1 1 1 1 1 1 1 1]
------------------------------------------------------------------------
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[1. 1. 1.]
 [1. 1. 1.]]


## arange()

In [15]:
a = np.arange(10)
b = np.arange(5, 10)
c = np.arange(5, 20, 3)
d = np.arange(5, 10, 1.5)
e = np.arange(5, 10, dtype='f4')
print(a, b, c, d, e)
print(a.dtype, b.dtype, c.dtype, d.dtype, e.dtype)

[0 1 2 3 4 5 6 7 8 9] [5 6 7 8 9] [ 5  8 11 14 17] [5.  6.5 8.  9.5] [5. 6. 7. 8. 9.]
int32 int32 int32 float64 float32


## linspace()

    np.linspace(start=, stop=, num=50, endpoint=True, retstep=False, dtype=None, axis=0)

In [16]:
l = np.linspace(start=0, stop=20, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
print(l)

# Default values: num=50, endpoint=True, retstep=False, dtype=None, axis=0

l = np.linspace(0, 98)
print(l)
print(f'l.size      =>  {l.size}')
print(f'l.ndim      =>  {l.ndim}')
print(f'l.dtype     =>  {l.dtype}')
print(f'l.shape     =>  {l.shape}')
print(f'l.itemsize  =>  {l.itemsize}')

l = np.linspace(0, 10, 5)
print(f'l           => {l}')
l = np.linspace(0, 20, 10, False)
print(f'l           => {l}')
l = np.linspace(0, 20, 5, endpoint=False)
print(f'l           => {l}')
l = np.linspace(0, 20, 5, endpoint=True, retstep=True)
print(f'l               => {l}')
print(f'array : l[0]    => {l[0]}')
print(f'retstep : l[1]  => {l[1]}')

[ 0.          0.40816327  0.81632653  1.2244898   1.63265306  2.04081633
  2.44897959  2.85714286  3.26530612  3.67346939  4.08163265  4.48979592
  4.89795918  5.30612245  5.71428571  6.12244898  6.53061224  6.93877551
  7.34693878  7.75510204  8.16326531  8.57142857  8.97959184  9.3877551
  9.79591837 10.20408163 10.6122449  11.02040816 11.42857143 11.83673469
 12.24489796 12.65306122 13.06122449 13.46938776 13.87755102 14.28571429
 14.69387755 15.10204082 15.51020408 15.91836735 16.32653061 16.73469388
 17.14285714 17.55102041 17.95918367 18.36734694 18.7755102  19.18367347
 19.59183673 20.        ]
[ 0.  2.  4.  6.  8. 10. 12. 14. 16. 18. 20. 22. 24. 26. 28. 30. 32. 34.
 36. 38. 40. 42. 44. 46. 48. 50. 52. 54. 56. 58. 60. 62. 64. 66. 68. 70.
 72. 74. 76. 78. 80. 82. 84. 86. 88. 90. 92. 94. 96. 98.]
l.size      =>  50
l.ndim      =>  1
l.dtype     =>  float64
l.shape     =>  (50,)
l.itemsize  =>  8
l           => [ 0.   2.5  5.   7.5 10. ]
l           => [ 0.  2.  4.  6.  8. 10. 12. 

## Operations between Arrays and Scalars

In [17]:
arr = np.arange(5)
print(arr)

arr **= 2
print(arr)

arr += 10
print(arr)

arr = arr - 15
print(arr)

arr = abs(arr)
print(arr)

print(arr.dtype)
arr = arr/2
print(arr)
print(arr.dtype)

arr = 1/arr
print(arr)

[0 1 2 3 4]
[ 0  1  4  9 16]
[10 11 14 19 26]
[-5 -4 -1  4 11]
[ 5  4  1  4 11]
int32
[2.5 2.  0.5 2.  5.5]
float64
[0.4        0.5        2.         0.5        0.18181818]


## numpy random

In [18]:
arr = np.random.randn(3, 4)
print(arr)

[[-1.03287019  0.28089781 -1.40855236  0.33292079]
 [ 2.04268741  0.6556036  -0.31914827  0.14896287]
 [-1.20177156 -0.25677142 -0.36661843  0.10974442]]


## Boolean Indexing

In [19]:
arr = np.random.randn(3, 4)
print(arr)
print(arr > 0)
arr[arr<0] += 10
print(arr)

[[ 1.36489669  1.36342314 -0.67119175 -0.34652222]
 [-0.23553349  1.1495907   1.33578787 -0.50508414]
 [-0.57359224  0.44291121 -0.79216799  0.23669787]]
[[ True  True False False]
 [False  True  True False]
 [False  True False  True]]
[[1.36489669 1.36342314 9.32880825 9.65347778]
 [9.76446651 1.1495907  1.33578787 9.49491586]
 [9.42640776 0.44291121 9.20783201 0.23669787]]


## Fancy indexing

In [20]:
arr = np.arange(1, 29).reshape(7, 4)

print(arr)
print(arr[1,2]) # row 1 - column 2 value
print("------------------------------------------------------------------------")

print(arr[[1,2,3]]) # prints rows 1, 2, and 3
print("------------------------------------------------------------------------")

# To select out a subset of the rows in a particular order, one can simply pass a list or ndarray of integers specifying the desired order.
print(arr[[4,3,0,6]])
print("------------------------------------------------------------------------")

arr[[4,3,0,6]] += 100 # This will also modify the original array
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]]
7
------------------------------------------------------------------------
[[ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
------------------------------------------------------------------------
[[17 18 19 20]
 [13 14 15 16]
 [ 1  2  3  4]
 [25 26 27 28]]
------------------------------------------------------------------------
[[101 102 103 104]
 [  5   6   7   8]
 [  9  10  11  12]
 [113 114 115 116]
 [117 118 119 120]
 [ 21  22  23  24]
 [125 126 127 128]]


In [21]:
# Passing multiple index arrays does something slightly different; it selects a 1D array of elements corresponding to each tuple of indices
print(arr[[-3, -5, -1]])
print("------------------------------------------------------------------------")

# Passing multiple index arrays does something slightly different; it selects a 1D array of elements corresponding to each tuple of indices
print(arr[[1, 5, 6, 2], [0, 3, 1, 2]])
# The elements (1, 0), (5, 3), (6, 1), (2, 2) will be selected

[[117 118 119 120]
 [  9  10  11  12]
 [125 126 127 128]]
------------------------------------------------------------------------
[  5  24 126  11]


## Some useful functions for numpy arrays
    sum
    max
    min
    all
    any

In [22]:
arr = np.arange(500)
print(f'sum(arr)    =>  {sum(arr)}')
print(f'max(arr)    =>  {max(arr)}')
print(f'min(arr)    =>  {min(arr)}')
print(f'all(arr)    =>  {all(arr)}')
print(f'any(arr)    =>  {any(arr)}')

sum(arr)    =>  124750
max(arr)    =>  499
min(arr)    =>  0
all(arr)    =>  False
any(arr)    =>  True


In [23]:
arr = np.arange(500)
print(f'np.sum(arr)    =>  {np.sum(arr)}')
print(f'np.max(arr)    =>  {np.max(arr)}')
print(f'np.min(arr)    =>  {np.min(arr)}')
print(f'np.all(arr)    =>  {np.all(arr)}')
print(f'np.any(arr)    =>  {np.any(arr)}')

np.sum(arr)    =>  124750
np.max(arr)    =>  499
np.min(arr)    =>  0
np.all(arr)    =>  False
np.any(arr)    =>  True


In [24]:
arr = np.arange(500000)
print(f'sum(arr)        =>  {sum(arr)}') # gives wrong answer # RuntimeWarning: overflow encountered in long_scalars
print(f'np.sum(arr)     =>  {np.sum(arr)}') # gives wrong answer
print(f'correct sum     =>  {499999 * 250000}')

arr = np.arange(500000, dtype='i8')
print(f'np.sum(arr)     =>  {np.sum(arr)}') # gives correct answer
print(f'sum(arr)        =>  {sum(arr)}') # gives correct answer

li = list(range(500000))
print(f'sum(li)         =>  {sum(li)}') # gives correct answer

sum(arr)        =>  445698416
np.sum(arr)     =>  445698416
correct sum     =>  124999750000
np.sum(arr)     =>  124999750000
sum(arr)        =>  124999750000
sum(li)         =>  124999750000


<ipython-input-24-8bf200c2e37e>:2: RuntimeWarning: overflow encountered in long_scalars
  print(f'sum(arr)        =>  {sum(arr)}') # gives wrong answer # RuntimeWarning: overflow encountered in long_scalars


## Universal functions (ufunc)

In [25]:
arr = np.arange(5)
arr = np.square(arr)
print(arr)

# arr.sqrt() # AttributeError: 'numpy.ndarray' object has no attribute 'sqrt'
arr = np.sqrt(arr)
print(arr)

arr = np.exp(arr)
print(arr)

print(np.log2(arr))
print(np.log10(arr))

arr = np.log(arr)
print(arr)
print("------------------------------------------------------------------------")

arr = np.random.randn(2, 3)
print(arr)
print(np.ceil(arr))
print(np.floor(arr))

[ 0  1  4  9 16]
[0. 1. 2. 3. 4.]
[ 1.          2.71828183  7.3890561  20.08553692 54.59815003]
[0.         1.44269504 2.88539008 4.32808512 5.77078016]
[0.         0.43429448 0.86858896 1.30288345 1.73717793]
[0. 1. 2. 3. 4.]
------------------------------------------------------------------------
[[-0.88430968  0.67126263  0.69388592]
 [-1.10640988  0.30988221  0.4881372 ]]
[[-0.  1.  1.]
 [-1.  1.  1.]]
[[-1.  0.  0.]
 [-2.  0.  0.]]


In [26]:
arr1 = np.linspace(30, 54, 9).reshape((3, 3))
arr2 = np.linspace(9, 81, 9).reshape((3, 3))
print(arr1)
print(arr2)
print("------------------------------------------------------------------------")

print(np.add(arr1, arr2))
print(arr1 - arr2)
print(np.multiply(arr1, arr2))
print(arr1 / arr2)
print(arr1 // arr2)
print("------------------------------------------------------------------------")

print(np.floor_divide(arr1, arr2) == arr1 // arr2)
print("------------------------------------------------------------------------")

[[30. 33. 36.]
 [39. 42. 45.]
 [48. 51. 54.]]
[[ 9. 18. 27.]
 [36. 45. 54.]
 [63. 72. 81.]]
------------------------------------------------------------------------
[[ 39.  51.  63.]
 [ 75.  87.  99.]
 [111. 123. 135.]]
[[ 21.  15.   9.]
 [  3.  -3.  -9.]
 [-15. -21. -27.]]
[[ 270.  594.  972.]
 [1404. 1890. 2430.]
 [3024. 3672. 4374.]]
[[3.33333333 1.83333333 1.33333333]
 [1.08333333 0.93333333 0.83333333]
 [0.76190476 0.70833333 0.66666667]]
[[3. 1. 1.]
 [1. 0. 0.]
 [0. 0. 0.]]
------------------------------------------------------------------------
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
------------------------------------------------------------------------


In [27]:
arr1 = np.linspace(30, 54, 9).reshape((3, 3))
arr2 = np.linspace(9, 81, 9).reshape((3, 3))
print(arr1)
print(arr2)
print("------------------------------------------------------------------------")

print(arr1 < arr2)
print("------------------------------------------------------------------------")

# Element wise maximum, fmax ignores NaN
print(np.maximum(arr1, arr2))
print(np.fmax(arr1, arr2))

# Element wise minimum, fmin ignores NaN
print(np.minimum(arr1, arr2))
print(np.fmin(arr1, arr2))
print("------------------------------------------------------------------------")

[[30. 33. 36.]
 [39. 42. 45.]
 [48. 51. 54.]]
[[ 9. 18. 27.]
 [36. 45. 54.]
 [63. 72. 81.]]
------------------------------------------------------------------------
[[False False False]
 [False  True  True]
 [ True  True  True]]
------------------------------------------------------------------------
[[30. 33. 36.]
 [39. 45. 54.]
 [63. 72. 81.]]
[[30. 33. 36.]
 [39. 45. 54.]
 [63. 72. 81.]]
[[ 9. 18. 27.]
 [36. 42. 45.]
 [48. 51. 54.]]
[[ 9. 18. 27.]
 [36. 42. 45.]
 [48. 51. 54.]]
------------------------------------------------------------------------


In [28]:
print(np.mod(arr1, arr2))
print(arr1%arr2)
print("------------------------------------------------------------------------")

print(np.power(arr1, arr2))
print(arr1**arr2)


[[ 3. 15.  9.]
 [ 3. 42. 45.]
 [48. 51. 54.]]
[[ 3. 15.  9.]
 [ 3. 42. 45.]
 [48. 51. 54.]]
------------------------------------------------------------------------
[[1.96830000e+013 2.15402588e+027 1.04753254e+042]
 [1.89812956e+057 1.11229009e+073 1.87704958e+089]
 [8.28319632e+105 8.81155749e+122 2.10811620e+140]]
[[1.96830000e+013 2.15402588e+027 1.04753254e+042]
 [1.89812956e+057 1.11229009e+073 1.87704958e+089]
 [8.28319632e+105 8.81155749e+122 2.10811620e+140]]


## Mathematical and statistical methods

In [29]:
arr = np.arange(1, 21).reshape(5, 4)
print(arr)
print(arr.mean(), np.mean(arr))
print(arr.mean(axis=0), np.mean(arr, axis=0))
print(arr.mean(axis=1), np.mean(arr, axis=1))
print(arr.mean(0), np.mean(arr, 1))
print("------------------------------------------------------------------------")

print(arr.sum(), np.sum(arr))
print(arr.sum(axis=0), np.sum(arr, axis=0))
print(arr.sum(axis=1), np.sum(arr, axis=1))
print(arr.sum(0), np.sum(arr, 1))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
10.5 10.5
[ 9. 10. 11. 12.] [ 9. 10. 11. 12.]
[ 2.5  6.5 10.5 14.5 18.5] [ 2.5  6.5 10.5 14.5 18.5]
[ 9. 10. 11. 12.] [ 2.5  6.5 10.5 14.5 18.5]
------------------------------------------------------------------------
210 210
[45 50 55 60] [45 50 55 60]
[10 26 42 58 74] [10 26 42 58 74]
[45 50 55 60] [10 26 42 58 74]


In [30]:
arr = np.arange(1, 9).reshape(4, 2)

print(arr.cumsum())
print(arr.cumsum(axis=0))
print(np.cumsum(arr, 1))
print("------------------------------------------------------------------------")

print(arr.cumprod())
print(arr.cumprod(axis=0))
print(np.cumprod(arr, 1))

[ 1  3  6 10 15 21 28 36]
[[ 1  2]
 [ 4  6]
 [ 9 12]
 [16 20]]
[[ 1  3]
 [ 3  7]
 [ 5 11]
 [ 7 15]]
------------------------------------------------------------------------
[    1     2     6    24   120   720  5040 40320]
[[  1   2]
 [  3   8]
 [ 15  48]
 [105 384]]
[[ 1  2]
 [ 3 12]
 [ 5 30]
 [ 7 56]]


In [31]:
arr = np.arange(1, 21).reshape(5, 4)
print(np.min(arr), arr.min())
print(np.max(arr), arr.max())
print(np.std(arr), arr.std())
print(np.var(arr), arr.var())
print(np.argmin(arr), arr.argmin())
print(np.argmax(arr), arr.argmax())

1 1
20 20
5.766281297335398 5.766281297335398
33.25 33.25
0 0
19 19


## Sorting

In [32]:
arr = np.random.randn(2, 3)
print(arr)
arr2 = np.sort(arr) # Out-place Sorting
print(arr2)
arr.sort() # In-place Sorting
print(arr)
print("------------------------------------------------------------------------")

arr.sort(1)
print(arr)
arr.sort(0)
print(arr)

[[ 0.8458679  -0.68870619  0.63692058]
 [ 2.27672022 -0.04740707 -0.79203225]]
[[-0.68870619  0.63692058  0.8458679 ]
 [-0.79203225 -0.04740707  2.27672022]]
[[-0.68870619  0.63692058  0.8458679 ]
 [-0.79203225 -0.04740707  2.27672022]]
------------------------------------------------------------------------
[[-0.68870619  0.63692058  0.8458679 ]
 [-0.79203225 -0.04740707  2.27672022]]
[[-0.79203225 -0.04740707  0.8458679 ]
 [-0.68870619  0.63692058  2.27672022]]


## File Input and Output with arrays

In [33]:
arr = np.array([np.random.randint(1, 5) for _ in range(12)]).reshape(3, 4)
print(arr)
np.save('myarr', arr)

[[4 4 3 2]
 [1 2 1 1]
 [1 2 4 2]]


In [34]:
arr = np.load('myarr.npy')
print(arr)

[[4 4 3 2]
 [1 2 1 1]
 [1 2 4 2]]


## Linear Algebra

In [35]:
arr = np.arange(1, 10).reshape(3, 3)
arr2 = np.arange(1, 4).reshape(3, 1)
print(arr)
print(arr2)
print("------------------------------------------------------------------------")

print(arr.dot(arr2))
print(np.dot(arr, arr2))
print(np.dot(arr, arr))
# print(np.dot(arr2, arr2)) # ValueError: shapes (3,1) and (3,1) not aligned: 1 (dim 1) != 3 (dim 0)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1]
 [2]
 [3]]
------------------------------------------------------------------------
[[14]
 [32]
 [50]]
[[14]
 [32]
 [50]]
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [36]:
arr = np.arange(1, 5).reshape(2, 2)
arr2 = np.arange(1, 4).reshape(3, 1)
print(arr)

arr3 = np.linalg.inv(arr)
print(arr3)
# arr3 = np.linalg.inv(arr2) # LinAlgError: Last 2 dimensions of the array must be square

print(np.trace(arr), arr.trace())
print(np.linalg.det(arr))

[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]
5 5
-2.0000000000000004
